import { Book } from '@/types/book'

export const BOOKS: Book[] = [
  {
    id: '1',
    thumbnail: 'https://unsplash.it/480?image=1',
    title: 'ダミーブック1',
    content: 'これはダミーブック1の内容です。',
    rate: 3.5,
    retailPrice: 1499,
    author: {
      id: '1',
      name: '著者1',
      description: 'これは著者1の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=1',
    },
  },
  {
    id: '2',
    thumbnail: 'https://unsplash.it/480?image=2',
    title: 'ダミーブック2',
    content: 'これはダミーブック2の内容です。',
    rate: 4.5,
    retailPrice: 1500,
    specialRetailPrice: 783,
    author: {
      id: '2',
      name: '著者22',
      description: 'これは著者2の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=2',
    },
  },
  {
    id: '3',
    thumbnail: 'https://unsplash.it/480?image=3',
    title: 'ダミーブック3',
    content: 'これはダミーブック3の内容です。',
    rate: 4.5,
    retailPrice: 1500,
    specialRetailPrice: 893,
    author: {
      id: '3',
      name: '著者3',
      description: 'これは著者3の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=3',
    },
  },
  {
    id: '4',
    thumbnail: 'https://unsplash.it/480?image=4',
    title: 'ダミーブック4',
    content: 'これはダミーブック4の内容です。',
    rate: 4.5,
    retailPrice: 1500,
    specialRetailPrice: 437,
    author: {
      id: '4',
      name: '著者4',
      description: 'これは著者4の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=4',
    },
  },
  {
    id: '5',
    thumbnail: 'https://unsplash.it/480?image=5',
    title: 'ダミーブック5',
    content: 'これはダミーブック5の内容です。',
    rate: 4.5,
    retailPrice: 1500,
    specialRetailPrice: 891,
    author: {
      id: '5',
      name: '著者5',
      description: 'これは著者5の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=5',
    },
  },
  {
    id: '6',
    thumbnail: 'https://unsplash.it/480?image=6',
    title: 'ダミーブック6',
    content: 'これはダミーブック6の内容です。',
    rate: 4.5,
    retailPrice: 1500,
    specialRetailPrice: 799,
    author: {
      id: '6',
      name: '著者6',
      description: 'これは著者6の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=6',
    },
  },
  {
    id: '7',
    thumbnail: 'https://unsplash.it/480?image=7',
    title: 'ダミーブック7',
    content: 'これはダミーブック7の内容です。',
    rate: 3.5,
    retailPrice: 1499,
    author: {
      id: '7',
      name: '著者7',
      description: 'これは著者7の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=7',
    },
  },
  {
    id: '8',
    thumbnail: 'https://unsplash.it/480?image=8',
    title: 'ダミーブック8',
    content: 'これはダミーブック8の内容です。',
    rate: 4.5,
    retailPrice: 1500,
    specialRetailPrice: 783,
    author: {
      id: '8',
      name: '著者8',
      description: 'これは著者8の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=8',
    },
  },
  {
    id: '9',
    thumbnail: 'https://unsplash.it/480?image=9',
    title: 'ダミーブック9',
    content: 'これはダミーブック9の内容です。',
    rate: 4.5,
    retailPrice: 1500,
    specialRetailPrice: 893,
    author: {
      id: '9',
      name: '著者9',
      description: 'これは著者9の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=9',
    },
  },
  {
    id: '10',
    thumbnail: 'https://unsplash.it/480?image=10',
    title: 'ダミーブック10',
    content: 'これはダミーブック10の内容です。',
    rate: 4.5,
    retailPrice: 1500,
    specialRetailPrice: 437,
    author: {
      id: '10',
      name: '著者10',
      description: 'これは著者10の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=10',
    },
  },
  {
    id: '11',
    thumbnail: 'https://unsplash.it/480?image=11',
    title: 'ダミーブック11',
    content: 'これはダミーブック11の内容です。',
    rate: 4.5,
    retailPrice: 1500,
    specialRetailPrice: 891,
    author: {
      id: '11',
      name: '著者11',
      description: 'これは著者11の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=11',
    },
  },
  {
    id: '12',
    thumbnail: 'https://unsplash.it/480?image=12',
    title: 'ダミーブック12',
    content: 'これはダミーブック12の内容です。',
    rate: 4.5,
    retailPrice: 1500,
    specialRetailPrice: 799,
    author: {
      id: '12',
      name: '著者12',
      description: 'これは著者12の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=12',
    },
  },
  {
    id: '13',
    thumbnail: 'https://unsplash.it/480?image=13',
    title: 'ダミーブック13',
    content: 'これはダミーブック13の内容です。',
    rate: 3.5,
    retailPrice: 1499,
    author: {
      id: '13',
      name: '著者13',
      description: 'これは著者13の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=13',
    },
  },
  {
    id: '14',
    thumbnail: 'https://unsplash.it/480?image=14',
    title: 'ダミーブック14',
    content: 'これはダミーブック14の内容です。',
    rate: 4.5,
    retailPrice: 1500,
    specialRetailPrice: 783,
    author: {
      id: '14',
      name: '著者14',
      description: 'これは著者14の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=14',
    },
  },
  {
    id: '15',
    thumbnail: 'https://unsplash.it/480?image=15',
    title: 'ダミーブック15',
    content: 'これはダミーブック15の内容です。',
    rate: 4.5,
    retailPrice: 1500,
    specialRetailPrice: 893,
    author: {
      id: '15',
      name: '著者15',
      description: 'これは著者15の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=15',
    },
  },
  {
    id: '16',
    thumbnail: 'https://unsplash.it/480?image=16',
    title: 'ダミーブック16',
    content: 'これはダミーブック16の内容です。',
    rate: 4.5,
    retailPrice: 1500,
    specialRetailPrice: 437,
    author: {
      id: '16',
      name: '著者16',
      description: 'これは著者16の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=16',
    },
  },
  {
    id: '17',
    thumbnail: 'https://unsplash.it/480?image=17',
    title: 'ダミーブック17',
    content: 'これはダミーブック17の内容です。',
    rate: 4.5,
    retailPrice: 1500,
    specialRetailPrice: 891,
    author: {
      id: '17',
      name: '著者17',
      description: 'これは著者17の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=17',
    },
  },
  {
    id: '18',
    thumbnail: 'https://unsplash.it/480?image=18',
    title: 'ダミーブック18',
    content: 'これはダミーブック18の内容です。',
    rate: 4.5,
    retailPrice: 1500,
    specialRetailPrice: 799,
    author: {
      id: '18',
      name: '著者18',
      description: 'これは著者18の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=18',
    },
  },
  {
    id: '19',
    thumbnail: 'https://unsplash.it/480?image=19',
    title: 'ダミーブック19',
    content: 'これはダミーブック19の内容です。',
    rate: 3.5,
    retailPrice: 1499,
    author: {
      id: '19',
      name: '著者19',
      description: 'これは著者19の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=19',
    },
  },
  {
    id: '20',
    thumbnail: 'https://unsplash.it/480?image=20',
    title: 'ダミーブック20',
    content: 'これはダミーブック20の内容です。',
    rate: 4.5,
    retailPrice: 1500,
    specialRetailPrice: 783,
    author: {
      id: '20',
      name: '著者20',
      description: 'これは著者20の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=20',
    },
  },
  {
    id: '21',
    thumbnail: 'https://unsplash.it/480?image=21',
    title: 'ダミーブック21',
    content: 'これはダミーブック21の内容です。',
    rate: 4.5,
    retailPrice: 1500,
    specialRetailPrice: 893,
    author: {
      id: '21',
      name: '著者21',
      description: 'これは著者21の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=21',
    },
  },
  {
    id: '22',
    thumbnail: 'https://unsplash.it/480?image=22',
    title: 'ダミーブック22',
    content: 'これはダミーブック22の内容です。',
    rate: 4.5,
    retailPrice: 1500,
    specialRetailPrice: 437,
    author: {
      id: '22',
      name: '著者22',
      description: 'これは著者22の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=22',
    },
  },
  {
    id: '23',
    thumbnail: 'https://unsplash.it/480?image=23',
    title: 'ダミーブック23',
    content: 'これはダミーブック23の内容です。',
    rate: 4.5,
    retailPrice: 1500,
    specialRetailPrice: 891,
    author: {
      id: '23',
      name: '著者23',
      description: 'これは著者23の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=23',
    },
  },
  {
    id: '24',
    thumbnail: 'https://unsplash.it/480?image=24',
    title: 'ダミーブック24',
    content: 'これはダミーブック24の内容です。',
    rate: 4.5,
    retailPrice: 1500,
    specialRetailPrice: 799,
    author: {
      id: '24',
      name: '著者24',
      description: 'これは著者24の説明です。',
      iconImagePath: 'https://unsplash.it/480?image=24',
    },
  },
]

export const GENRE = [
  {
    value: 'next.js',
    label: 'Next.js',
  },
  {
    value: 'sveltekit',
    label: 'SvelteKit',
  },
  {
    value: 'nuxt.js',
    label: 'Nuxt.js',
  },
  {
    value: 'remix',
    label: 'Remix',
  },
  {
    value: 'astro',
    label: 'Astro',
  },
]
