import type { Metadata } from 'next'
import { Noto_Sans_JP } from 'next/font/google'
import { twMerge } from 'tailwind-merge'
import './globals.css'

const notoSansJP = Noto_Sans_JP({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Book Commerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={twMerge('h-screen', notoSansJP.className)}>
        {children}
      </body>
    </html>
  )
}
